package null; // TODO: Update my package!

import java.util.ArrayList;
import java.util.List;

// TODO: Add my imports!

// WARNING:
// This file was autogenerated by FizzyApple12's StateGenerator
// !!!Edit at your own risk!!!
public class {$ClassName} {
    public static List<StateConnection<{$StateName}>> connections = new ArrayList<>() {{
        {$Connections}
    }};
}
